In [12]:
import csv
import numpy as np
from collections import Counter
import time

In [7]:
file = open("C:\\Users\\Simeon Horner\\Documents\\GitHub\\RiskAndLogisticsA2\\Data Files\\CSV versions\\OrderList.csv", encoding="utf-8")
csvreader = csv.reader(file)

Orders = []

for row in csvreader:
    Orders.append([int(x) for x in row[1:]])

Distances = np.genfromtxt('C:\\Users\\Simeon Horner\\Documents\\GitHub\\RiskAndLogisticsA2\\Data Files\\CSV versions\\DistanceMatrix_meters.csv', delimiter=',', skip_header=0, dtype='i')
Distances[0, 0] = 0

In [8]:
print(Distances)

[[ 0  3  6 ... 81 84  6]
 [ 3  0  3 ... 84 81  9]
 [ 6  3  0 ... 81 78 12]
 ...
 [81 84 81 ...  0  3 75]
 [84 81 78 ...  3  0 78]
 [ 6  9 12 ... 75 78  0]]


In [9]:
def getMostCommonProducts(Orders):
    #flattens list and removes 0
    flattenedList = [x for x in [item for sublist in Orders for item in sublist] if x != 0]

    #gets counts for products
    itemCounts = Counter(flattenedList)

    #sorts and returns only original number, not the count
    sorted_items = sorted(itemCounts.items(), key=lambda x: x[1], reverse=True)
    original_numbers = [item for item, _ in sorted_items]

    return original_numbers
    

def getClosestShelves(Distances):
    #Gets the final row of the matrix as this represents the distance to door (packaging)
    distanceToDoor = Distances[-1]

    #gets the index, and distance
    indexed_numbers = list(enumerate(distanceToDoor))

    #sorts based on distance and then takes only the index
    sorted_indexed_numbers = sorted(indexed_numbers, key=lambda x: x[1])
    sorted_indexes = [index for index, _ in sorted_indexed_numbers]

    #ignores the first value as this is the door -> door distance = 0
    return sorted_indexes[1:]

def ConstructionHeuristic_mostCommonOrder(Orders, Distances):
    mostCommonProducts = getMostCommonProducts(Orders)

    ClosestShelves = getClosestShelves(Distances)

    print(ClosestShelves)
    newShelves = [0]*96
    counter = 0

    for i, shelf in enumerate(ClosestShelves):

        newShelves[shelf] = mostCommonProducts[counter]
        counter += 1

        if counter == len(mostCommonProducts):
            counter = 0

    return newShelves
    

In [14]:

start = time.time()
shelves = ConstructionHeuristic_mostCommonOrder(Orders, Distances)
end = time.time()

print(end-start)

print(shelves)

[0, 24, 1, 25, 48, 72, 2, 26, 49, 73, 3, 27, 50, 74, 4, 28, 51, 75, 5, 29, 52, 76, 6, 30, 53, 77, 7, 31, 54, 78, 8, 32, 55, 79, 9, 33, 56, 80, 10, 34, 57, 81, 11, 35, 58, 82, 12, 36, 59, 83, 13, 37, 60, 84, 14, 38, 61, 85, 15, 39, 62, 86, 16, 40, 63, 87, 17, 41, 64, 88, 18, 42, 65, 89, 19, 43, 66, 90, 20, 44, 67, 91, 21, 45, 68, 92, 22, 46, 69, 93, 23, 47, 70, 94, 71, 95]
0.0026404857635498047
[34, 35, 18, 2, 50, 11, 48, 60, 19, 44, 47, 64, 74, 68, 69, 21, 88, 14, 36, 53, 26, 3, 7, 34, 31, 71, 30, 58, 49, 28, 33, 43, 1, 59, 66, 46, 65, 90, 16, 45, 27, 80, 75, 61, 40, 86, 42, 31, 70, 51, 67, 4, 10, 52, 8, 63, 13, 72, 20, 32, 89, 82, 87, 24, 54, 9, 25, 62, 73, 17, 35, 70, 15, 76, 6, 83, 38, 78, 55, 39, 57, 37, 84, 77, 79, 29, 22, 5, 23, 56, 12, 41, 85, 81, 71, 15]
